name: Validate TSOA

on: [pull_request]

jobs:
  build:
    name: "Validate TSOA"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run TSOA build
        working-directory: ./back
        run: |
          yarn build-tsoa
          git diff --exit-code || (echo "❌ ERROR: TSOA routes are not up to date. Please run 'yarn build-tsoa' and commit the changes." && exit 1)